### PR TITLE
await client.SendCodeRequestAsync Null reference expection 

### PR DESCRIPTION
**Pull request by TERMI80**

### CODE REVIEW

**Comment by TERMI80** [comment]
I hope this time it's ok

**Comment by knocte** [comment]
You didn't understand what I asked you. I didn't ask you to upload your project as a pull request, I asked you to upload your FIX as a pull request. If you find a fix for the NullReferenceException, please upload it.

**Comment by TERMI80** [comment]
I haven'T a fix and i ask you tour help to solve or do you have some project for test your library not only class project?

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by knocte** [comment]
I said I cannot help because I cannot reproduce your problem.

**Comment by TERMI80** [comment]
Ok,
But can give me some example of string connection code?
Thanks

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Pull request closed without merging**
