### PR TITLE
TL Vector Enumerable

### PR DESCRIPTION
**Pull request by aarani**

### CODE REVIEW

**Comment by aarani** [comment]
Build fail is because of NUnit and not these commits

**Comment by knocte** [comment]
> Build fail is because of NUnit

I don't understand. The build was passing in the PR (https://github.com/sochix/TLSharp/pull/289) and the AppVeyor badge is green, it says the build passes.

**Comment by aarani** [comment]
@knocte i can't undrestand too 😞

**Comment by sochix** [comment]
Will, review later

**Comment by barsham** [comment]
I am afraid that you missed the reference to UnitTestFramework in your TLSharp.Tests project.
Basically what I can see is that you have change the Test project nature to Visual Studio Unit Test so you need to update the project changes in the Pull Request too.

image

**Comment by aarani** [comment]
This pull request was older than New Test Project Merged and i decided to
not Update pull request

**Pull request closed without merging**
