### PR TITLE
Connect through http proxy authentication

### PR DESCRIPTION
**Pull request by wolvewilson**
Example of use:

       TelegramClient client;

        bool useProxy = true;
        int apiId = 0;
        string apiHash = "";
        string apiPhone = "";
        string httpProxyHost = "";
        int httpProxyPort = 0;
        string proxyUsername = "";
        string proxyUserPwd = "";

        if (useProxy)
            client = new TelegramClient(apiId, apiHash, httpProxyHost, httpProxyPort, proxyUsername, proxyUserPwd);
        else
            client = new TelegramClient(apiId, apiHash);
        await client.ConnectAsync();

### CODE REVIEW

**Comment by Ansel1990B** [comment]
ReconnectToDcAsync  to solve the problem transport

**Comment by wolvewilson** [comment]
@Ansel1990B  i´ll correct it. Tks for your report :)

**Comment by knocte** [comment]
The diff is unreadable, did you use different line endings?

**Comment by wolvewilson** [comment]
@knocte i´m using the VS Community 2015, in Windows 10... i´ll check it too

**Comment by knocte** [comment]
Do you understand the problem I have? I cannot review the diff. Look at the diff yourself in github and you'll see what I mean.

**Comment by sochix** [comment]
@wolvewilson please do something with diffs, it's completely unreadable

**Comment by knocte** [comment]
Handy tools to fix this are: unix2dos or dos2unix.

**Comment by wolvewilson** [comment]
i tried to help.
I give up

**Pull request closed without merging**
