### PR TITLE
TelegramClient.ResolveUsernameAsync

### PR DESCRIPTION
**Pull request by ArmeF97**

### CODE REVIEW

**Comment by knocte** [comment]
Why? The consumer of TLSharp should remove the '@' character at the beginning.

**Comment by ArmeF97** [comment]
The PR is not for removing the @ at the beginning, is to introduce the whole function, that was not present

**Comment by knocte** [comment]
Oh sorry I thought you were introducing a new overload. Can you port your PR over to TgSharp please? TLSharp is deprecated because it uses an old layer.

**Comment by ArmeF97** [comment]
I suppose you are referring to this https://github.com/nblockchain/TgSharp

Thanks. Didnt' know about this

**Comment by knocte** [comment]
Yes

**Pull request closed without merging**
