### PR TITLE
Fix dc loop #719

### PR DESCRIPTION
**Pull request by ArmeF97**
Inserting a counter, after "times", throws an exception, that should be handled

### CODE REVIEW

**Comment by ArmeF97** [comment]
Maybe it's a fix for #719

**Comment by maurodx** [comment]
Probably this PR can't be accepted because you change all the async-await and also .NET Framework version, methods name, etc...

**Comment by ArmeF97** [comment]
> 
> 
> Probably this PR can't be accepted because you change all the async-await and also .NET Framework version, methods name, etc...

I'm sorry, I don't know how github works... I did the pull request with the first commit, than I did some commits to my fork, as a test, I didn't know that they were going to be added to this pr

**Comment by ArmeF97** [comment]
Should I do a new branch with just that commit?

**Comment by knocte** [comment]
@ArmeF97 sorry for the late reply, but I committed a different approach in master branch, see here: 60a3c6235792163e9c74e9c24b1ca7800a220ce2

**Comment by ArmeF97** [comment]
@knocte no problem. I'm glad I was of help. I'm sorry I didn't know how github works in pr... 

Now I now more and can help in future! 👍

**Pull request closed without merging**
