### PR TITLE
added while loop to MakeAuthAsync method to fix PhoneMigrationException.(fix for #458)

### PR DESCRIPTION
**Pull request by AmiNadim**
PhoneMigrationException in MakeAuthAsync() Bug fix.
added a while loop to make retries when Registering fails.
(fix for #458)

### CODE REVIEW

**Comment by knocte** [comment]
Thanks for the bugfix AmiNadim! Can you please specify in the commit message the issue you're fixing? You would just need to include the text (fix for #458) in the 3rd line of the commit message.

(To do this, you don't need to open a new PullRequest. You can use `git rebase -i HEAD~1`, then replace the word "pick" with "r", then amend the commit message, then `git push <remoteName> master -f`. Thanks

**Comment by AmiNadim** [comment]
yes! I will update my comments as soon as possible.

**Comment by AmiNadim** [comment]
I did it on my forked version but it seems rebasing has some problems. i cant pull back my editions after rebase as it says my branch is clear and not changed!
however i re-corrected the comment and merged the editions. shall i make a pull request now or you suggest a fix for the problem?

**Comment by knocte** [comment]
> shall i make a pull request now or you suggest a fix for the problem?

Not sure if it's the same problem you're talking about, but this PR has now 3 commits instead of 1. I suggest you try to fix this problem by doing `git rebase -i HEAD~3` and replacing the word "pick" in the last 2 commits with the word "squash", this will merge all commits into 1 and you can push again with the -f argument (you don't need to pull).

**Comment by AmiNadim** [comment]
[detached HEAD b7e2e9e] Update README.md
 Author: Ilya Pirozhenko <ilya.pir@gmail.com>
 Date: Thu May 4 18:01:13 2017 +0300
 2 files changed, 37 insertions(+), 8 deletions(-)
Successfully rebased and updated refs/heads/master.

I think someone had a commit and i'm rebasing theirs too! i think using HEAD~2 is a better choice. am i right ?

**Comment by knocte** [comment]
I see a merge-commit, which was maybe caused by you doing a `git pull` without a `--rebase` argument.

Maybe merge-commits are not taken in account when doing a rebase, so maybe you're right that HEAD~2 is better than HEAD~3. However, if this is true, then rebasing is not a solution to remove the merge commit.

I'm not sure how you can remove a merge commit. Maybe it's easier if you create a new PR.

**Comment by AmiNadim** [comment]
I think this should do the trick.

**Comment by knocte** [comment]
Mmm, there are some hunks in the diff that are unwanted, can you remove them?

**Comment by AmiNadim** [comment]
clean and ready!

**Comment by knocte** [comment]
Thanks for your contribution AmiNadim!

**Pull request merged**
