### PR TITLE
Added SignUp Request

### PR DESCRIPTION
**Pull request by eaba**

### CODE REVIEW

**Comment by eaba** [comment]
Hello @sochix, i need your input!
When registering new number, it is successful, i get the id
But some how i cant sendcode to the new new member via sms

**Comment by sochix** [comment]
Pls, fix build first

**Comment by eaba** [comment]
Hi @sochix can you spare a few minutes to look at the connect method?
I am experiencing deadlock on it which could be due to how async/wait is being used
Thanks

**Comment by eaba** [comment]
Hi @sochix I noticed something.
I can register user with the added request and with my DC it exists after registration
But when I try to add it as a contact from the official client connected to a different DC it says,
The number is not Telegram!
@sochix Please spare few minutes to into some issues too!

**Comment by eaba** [comment]
Please @sochix  SPARE FOR MINUTES TO ATTEND TO OPENED ISSUES!!, It encourages a lot!

**Comment by knocte** [comment]
@eaba, IMNSHO you're mixing too many things in this pull request. When you're contributing to a project, to make it easier to review you have to split your contributions so that each of them has a specific purpose. In this case: you should create PR for SendSmsRequest, and remove the commits related to SendSMSRequest from this PR. Same for the ImportContactByPhoneNumber() changes.

**Comment by eaba** [comment]
That was not intentional!
As i added to my fork, github added it to my earlier pull request which is yet to be committed!

**Comment by knocte** [comment]
Hehe fair enough. For this to not happen again, you shouldn't work in your master branch of your fork, but in different branches :)

**Comment by knocte** [comment]
You should then close this PR and open subsequent ones.

**Pull request closed without merging**
