### PR TITLE
Add Session readonly field to TelegramClient

### PR DESCRIPTION
**Pull request by MojtabaTajik**
Add Session readonly field which let user read session properties like current logedin user's Username & etc.

### CODE REVIEW

**Comment by knocte** [comment]
Make it a {get}-only property, not a field, please.

**Comment by MojtabaTajik** [comment]
> Make it a {get}-only property, not a field, please.

It's already get only. The code is expression bodied style of get only.

**Comment by knocte** [comment]
I would prefer to make it explicit just in case (more verbose but more readable).

**Comment by MojtabaTajik** [comment]
@knocte Done

**Comment by knocte** [comment]
Now the git commit message doesn't contain the good description that you had added before: "Add Session readonly field which let user read session properties like current logged-in user's Username & etc.". Please add it.

**Comment by knocte** [comment]
I said the commit message, not the PR title.

**Comment by knocte** [comment]
Do you need help with interactive rebase?

**Comment by knocte** [comment]
@MojtabaTajik I merged your improvement manually in the master branch: https://github.com/sochix/TLSharp/commit/8a15feea7c9357aab5bf6df504d45ae2077009d4

**Pull request closed without merging**
