### PR TITLE
Catch PhoneMigrationException in IsPhoneRegisteredAsync

### PR DESCRIPTION
**Pull request by unn4m3d**

### CODE REVIEW

**Comment by knocte** [comment]
Looks good to me. This would fix issue #290.

@sochix can you merge?

**Comment by sochix** [comment]
Thanks @unn4m3d ! Thanks @knocte for review

**Comment by knocte** [comment]
@sochix did you close without merging by mistake? :)

**Comment by sochix** [comment]
@knocte yep!

**Pull request merged**
