### PR TITLE
Update Everything 

### PR DESCRIPTION
**Pull request by aarani**
Hey Everybody ,<br>
 I finally finished this one and i decide to put this in github .<br>
 I Create my own (De)Serializer and Generator To Do this in Best Way .<br>
 Now Layer is Uptodate(Layer 53).
 But For Every Request You Must Wrote your MTProtoRequest Same as what i did for SendCode - SignIn - InitConnection.

Sincerly , ***Afshin Arani***

### CODE REVIEW

**Comment by aarani** [comment]
@sochix @steavy29

**Comment by steavy29** [comment]
Um. Very hard to review: almost each file is like removed and then added.

**Comment by steavy29** [comment]
Could you please explain what is Layer53? On telegram documentation page the latest one is only 23. Also a link to any documentation re. this would be very helpful

**Comment by aarani** [comment]
@steavy29 Telegram Stop Documenting on Layer 23 and lot of improvement happen like support channels and etc remain undocumented :sad and only way to access it  is using [THIS LINK](https://github.com/zhukov/webogram/blob/master/app/js/lib/config.js#L101)

**Comment by steavy29** [comment]
Now I see. Thanks for the link.

**Comment by aarani** [comment]
Even SharpTL that Sochix linked in Readme.md can't support this layer beacuse some variable are flag base that sharptl won't know even WHAT are Them and @badoualy help me to undrestand it .

Reason that nearly all files changed is i redesigned everything , except mtproto part beacuse i haven't enough time

**Comment by aarani** [comment]
idk why but i didn't delete all files 😮

**Comment by aarani** [comment]
I Create a new Pull Request to solve that problem @steavy29 mentioned #216

**Pull request closed without merging**
