### PR TITLE
Update to .NET Framework 4.6

### PR DESCRIPTION
**Pull request by aarani**

### CODE REVIEW

**Comment by knocte** [comment]
Great, but let me double check something first.

By the way what's your username in telegram?

**Comment by aarani** [comment]
> Great, but let me double check something first.
> 
> By the way what's your username in telegram?

I don't have one because of my privacy settings. Give me yours I will send a message to you.

**Comment by knocte** [comment]
> I don't have one because of my privacy settings. Give me yours I will send a message to you.

My username in telegram is the same as my username in github.

> Btw please remove appvoyer check from this repository.

Let's talk about this on telegram.

**Comment by knocte** [comment]
Merged manually https://github.com/sochix/TLSharp/commit/709e5be7ccaacdb74bd0c2d595d594e6a6aa8d2e

**Pull request closed without merging**
