### PR TITLE
Added an IPv4/IPv6 toggle to TelegramClient constructor

### PR DESCRIPTION
**Pull request by solarin**
that allows choosing whether to accept ipv4 or ipv6 or both ip address versions passed by the Telegram server.

### CODE REVIEW

**Comment by knocte** [comment]
Can you revert the change to the .sln file? It's what's causing the build to fail.

**Comment by aarani** [comment]
You added a project to the solution that you added to .gitignore.
First of all please revert the changes to gitignore and second exclude the project from Solution file.

**Comment by solarin** [comment]
sure, let me do it. sorry guys, i haven't used github frequently

**Comment by solarin** [comment]
by the way, if you guys agree I would rename the enum to DataCenterIPvPrefs or DataCenterIPVersions

**Comment by solarin** [comment]
moved to 925 https://github.com/sochix/TLSharp/pull/925/

**Pull request closed without merging**
