### PR TITLE
Fix V3029 warnings from PVS-Studio Static Analyzer

### PR DESCRIPTION
**Pull request by AdmAlexus**
Hello. I'm a member of the Pinguem.ru competition on finding errors in open source projects. A bug, found using PVS-Studio.

Maybe I did not fully understand the code, but it seems to me there were superfluous checks on the conditions.

Warnings with low priority:

[V3029](https://www.viva64.com/en/w/v3029/) The conditional expressions of the 'if' statements situated
alongside each other are identical. Check lines: 69, 71.
TLPasswordInputSettings.cs 69

[V3029](https://www.viva64.com/en/w/v3029/) The conditional expressions of the 'if' statements situated
alongside each other are identical. Check lines: 71, 73.
TLPasswordInputSettings.cs 71

[V3029](https://www.viva64.com/en/w/v3029/) The conditional expressions of the 'if' statements situated
alongside each other are identical. Check lines: 91, 93.
TLPaymentForm.cs 91

[V3029](https://www.viva64.com/en/w/v3029/) The conditional expressions of the 'if' statements situated
alongside each other are identical. Check lines: 120, 122.
TLBotInlineResult.cs 120

[V3029](https://www.viva64.com/en/w/v3029/) The conditional expressions of the 'if' statements situated
alongside each other are identical. Check lines: 124, 126.
TLBotInlineResult.cs 124

[V3029](https://www.viva64.com/en/w/v3029/) The conditional expressions of the 'if' statements situated
alongside each other are identical. Check lines: 124, 126.
TLChannelFull.cs 124

[V3029](https://www.viva64.com/en/w/v3029/) The conditional expressions of the 'if' statements situated
alongside each other are identical. Check lines: 120, 122.
TLInputBotInlineResult.cs 120

[V3029](https://www.viva64.com/en/w/v3029/) The conditional expressions of the 'if' statements situated
alongside each other are identical. Check lines: 124, 126.
TLInputBotInlineResult.cs 124

[V3029](https://www.viva64.com/en/w/v3029/) The conditional expressions of the 'if' statements situated
alongside each other are identical. Check lines: 154, 156. TLWebPage.cs
154

[V3029](https://www.viva64.com/en/w/v3029/) The conditional expressions of the 'if' statements situated
alongside each other are identical. Check lines: 158, 160. TLWebPage.cs
158

### CODE REVIEW

**Comment by knocte** [comment]
@aarani: are these parts of the code autogenerated?

**Comment by aarani** [comment]
@knocte: Yes, whole TeleSharp.TL namespace is generated

**Comment by knocte** [comment]
Thanks @aarani. Then, @AdmAlexus thanks for your contribution but it's not very useful because it would get undone next time we autogenerate TeleSharp.TL :(

**Comment by AdmAlexus** [comment]
@knocte Ok. Thx 2 you.

**Pull request closed without merging**
