### PR TITLE
Updated to the latest scheme

### PR DESCRIPTION
**Pull request by XyLoNaMiyX**
.tl files compiler created, everything updated to the latest scheme.
Classes "TBinaryReader" and "TBinaryWriter" created to emulate Telegram
BinaryReader/BinaryWriter

### CODE REVIEW

**Comment by sochix** [comment]
Don't understand how actually it compile smthng, describe please.

**Comment by XyLoNaMiyX** [comment]
It takes .tl files (such as [https://core.telegram.org/schema](https://core.telegram.org/schema)) and turns them into CSharp code. Basically, it keeps the structure you've been using until now.

For example:
`inputPeerEmpty#7f3b18ea = InputPeer;`

Turns into:
```csharp
public class InputPeerEmptyType : InputPeer
{
    public override uint ConstructorCode => 0x7f3b18ea;

    public InputPeerEmptyType() { }

    public override void Write(TBinaryWriter writer)
    {
        writer.Write(ConstructorCode);
    }

    public override void Read(TBinaryReader reader)
    {
    }

    public override string ToString()
    {
        return "(InputPeerEmptyType)";
    }
}
```

I made an abstract implementation of a compiler class so any kind of compiler (for example, a compiler for JavaScript could be made) can be made. In this case, I've implemented a CSharp code compiler.

**Comment by sochix** [comment]
What is TBinaryWriter or TBinaryReader in your example?

**Comment by XyLoNaMiyX** [comment]
Instead using a `Serializer` class, I've instead made a class that implements a `BinaryWriter & BinaryReader`, so they act like your old `Serializer` class. They do the same, but makes the code more readable in my opinion.

**Comment by sochix** [comment]
@XyLoNaMiyX pls, try to fix a build

**Comment by XyLoNaMiyX** [comment]
Sorry, what did you mean?

**Comment by eaba** [comment]
@XyLoNaMiyX he meant your pull cannot be merged because it is conflicting with @sochix master branch. Look at what is wrong and correct it

**Comment by XyLoNaMiyX** [comment]
Closing this since the "updated version" of the branch is now pointed out under #197

**Pull request closed without merging**
