### PR TITLE
TL-Layer: Update To Layer 66

### PR DESCRIPTION
**Pull request by aarani**
#518

### CODE REVIEW

**Comment by knocte** [comment]
Hey @aarani, there are inconsistencies in the whitespace/indentation used. Can you fix it?

**Comment by sochix** [comment]
@knocte if you're not against I will merge it, as it really great commit

**Comment by nazarianazad** [comment]
@sochix please merge it as soon as possible, I'm working on this project to add many methods
 and I want to save my changes after this commit

**Comment by aarani** [comment]
[DON'T MERGE] I will fix indentation first.

**Comment by aarani** [comment]
@sochix @knocte Indentation Fixed! 👍

**Comment by knocte** [comment]
@sochix @aarani looks great now, merging

**Comment by knocte** [comment]
@aarani only nitpick I see with this generated code is that it's using lowercase_with_underscore naming style for public members, which goes against the recommended API guidelines & practices from Microsoft. Any chance we can fix that too?

**Comment by aarani** [comment]
@knocte I will check if I can fix The Code Generator.

**Comment by mirror-neuron** [comment]
@knocte please update latest-scheme-link in Readme.md to aarani file with 66 version, thanks.
https://gist.github.com/aarani/702232928ef06cbd7cefacfbc73b71c8

**Pull request merged**
