### PR TITLE
Redesigned TLSharp With Layer 53

### PR DESCRIPTION
**Pull request by aarani**
Hey Everybody ,<br>
 I finally finished this one and i decide to put this in github .<br>
 I Create my own (De)Serializer and Generator To Do this in Best Way .<br>
 Now Layer is Uptodate(Layer 53).
 But For Every Request You Must Wrote your MTProtoRequest Same as what i did for SendCode - SignIn - InitConnection.

Sincerly , ***Afshin Arani***

### CODE REVIEW

**Comment by aarani** [comment]
@steavy29  @sochix  Look New one pls.

**Comment by steavy29** [comment]
Diff shows that you removed a lot of requests. Also in `TelegramClient` they appear to be commented out. Could you explain this point please? Or maybe I missed something.

**Comment by aarani** [comment]
@steavy29 actually all previous request need to re-implant and i can't do it alone .

**Comment by steavy29** [comment]
Actually I thought that one could even implement some generator for all requests, not just serializing types. They are quite template-like.

**Comment by aarani** [comment]
@steavy29 Actually i haven't enough time and good mood 😆 to do it . you can do it with forking my [TL.Generator](http://github.com/aarani/TeleSharp.TL/)

**Comment by sochix** [comment]
Hi! Nice work done! But, I can't merge it: you removed Test project and a lot of old requests. Sorry.

**Comment by aarani** [comment]
@sochix What i want is that you merge it into new branch to start working on it .

**Comment by sochix** [comment]
Ok, i got your idea. I'll create a new branch

**Comment by sochix** [comment]
@aarani where I can get latest tl schema for your generator?

**Comment by aarani** [comment]
@sochix . [Here](https://github.com/zhukov/webogram/blob/master/app/js/lib/config.js#L101)

**Comment by aarani** [comment]
I redesigned Everything from first and there is no need to use
MTProtoRequest anymore . Just call the function u want and get answer from
it . Except login and register and initialize because those are hard for
user to understand . I will upload it tomorrow @sochix this time I didn't
delete test project ☺️😉.


P.S : @sochix unblock me in telegram

**Comment by aarani** [comment]
@sochix Take a Look

**Comment by sochix** [comment]
@aarani what is your nickname in telegram?

**Comment by aarani** [comment]
Afshin Arani

**Pull request merged**
