### PR TITLE
Convert TLVector to Enumerable 

### PR DESCRIPTION
**Pull request by aarani**
Why ?  
Using ".lists" for every line of code is very annoying so i just convert TLVector To Enumerable.

### CODE REVIEW

**Comment by knocte** [comment]
Why are you doing so many casts? The List is generic so you don't need casts.

**Comment by aarani** [comment]
It's Visual Studio's Generated Code Not Mine

**Comment by knocte** [comment]
Anyway you're mixing things here, you added the CloudPassword support commit.

**Comment by sochix** [comment]
Yep, agreed with @knocte. @aarani can you please factor out cloud passwords from this pull-request?

**Pull request closed without merging**
