### PR TITLE
Make TLVector Implement IList

### PR DESCRIPTION
**Pull request by aarani**
@knocte It will make codes lot simpler

### CODE REVIEW

**Comment by aarani** [comment]
@knocte I have to say these last 2 commit (this and other merged one) will need changes in README

**Comment by knocte** [comment]
Good catch! Can you add those changes in this PR?

**Comment by aarani** [comment]
@knocte Sorry i have no time to do that but you can easily use TLSharpTests file to do changes

**Comment by knocte** [comment]
Ok, will do next week.

**Pull request merged**
